### ISSUE TITLE
Map generates extra on right

### ISSUE THREAD

**Issue by Jacob-Guglielmin** [CelestialTater/legendary-goggles#5]

**Comment by CelestialTater** [comment]
Resolved in latest commit

**Comment by Jacob-Guglielmin** [comment]
This issue is caused by the else if statements running only if the previous one fails. If any check passes that allows it to print a period in a part of the array that does not exist, then it prints a period and adds to the array.

**Comment by CelestialTater** [comment]
proper fix coming in in a few mins

**Comment by CelestialTater** [comment]
should now be fixed
